---
title: "BankChurnPrediction"
author: "Ananda Poudel"
date: "3/29/2021"
output: html_document
---

# Libraries and setting directory
```{r}
setwd("/Users/apoudel53/Desktop/Job Search/project")
churn <- read.csv("churn.csv")
library(caret)
library(dplyr)
library(ROSE)
```

# Data wrangling
```{r}
#Checking for blank values
sapply(colnames(churn), function(x){
  sum(is.na(churn[,x]) | churn[,x] == '')
})
#Looks like we have no missing data or NA values which is amazing

#Remove columns 1, 2 and 3 from the dataset as we don't need them for a machine learning model.
df <- churn[,-c(1:3)]
#Setting a new variable because we will need to use churn for visualization later on.

#Looking at data types
str(df)
#Need to convert some variables into factors for the model.
df$Geography <- as.factor(df$Geography)
df$Gender <- as.factor(df$Gender)
#We can leave age as a continuous variable for now but if the model isn't accurate, we can group age into distinct factors.
df$HasCrCard <- as.factor(df$HasCrCard)
df$IsActiveMember <- as.factor(df$IsActiveMember)
df$Exited <- as.factor(df$Exited)
str(df)

#Checking for class imbalance
table(df$Exited) %>% prop.table()

#The response variable does seem to be imabalanced. We will create multiple df with distinct sampling methods and compare each model based on the sampling method to determine which model has the best accuracy later when we create our models.

```

#


# Creating a dashboard for visualization in RShiny

```{r}
#Make three tabs, first one for distinct visualization to compare between different features, second one for individual customer visualization and third one for a prediction model.
```

